### ISSUE TITLE
68000: shift operations have incorrect flags

### ISSUE THREAD

**Issue by invertego** [TomHarte/ProcessorTests#19]
The C, X, and V bits appear to be wrong in a lot of cases for shift operations. Some examples:

"e327 [ASL.b D1, D7] 7"
initial d1: 0xD462DA67 d7: 0x3BBDD492
final d7: 0x3BBDD400 sr: 0x2717
Effectively 0x92 << 0x27 = 0, yet both the C and X bits are set in the final state.

"e502 [ASL.b Q, D2] 42"
intial d2: 0xAA7B9CD7
final d2: 0xAA7B9C5C sr: 0x2711
Effectively 0xD7 << 2 = 0x5C, yet the V bit is not set in the final state.

**Comment by TomHarte** [comment]
Indeed, I'd fallen into the trap of undefined behaviour with the test generator — shifting by quantities greater than the underlying integer size.

#20 is intended to address this, though I intend to do some further manual verification before merging.
