### ISSUE TITLE
Something wrong with the 680x0 tests or I don't undestand how it works?

### ISSUE THREAD

**Issue by pi1541** [TomHarte/ProcessorTests#23]
I'm very confused, please help me understand.
The first test I tried for 680x0 in ABCD.json looks confusing.
It is testing "ABCD.B -(A5),-(A6)" 
The initial A5 is 281750813 and A6 is 270492367.
The initial and final memory sections do not specify the values of the addresses 281750813 or 270492367 so I don't know how the information in the JSON helps to test this instruction.
The memory sections do however specify value of some other random address 2056910 (not referenced by any of the initial registers) with the initial and final values being different (but this is no where near where A6 is pointing to)
The final values for A5 and A6 have correctly been decremented but the "transaction" section indicates that it does not read from the addresses they point to.
Instead it says there is a read from 13315356 and 2056910 then a write to 2056910.
I assume the initial A5 should be 13315356 and the initial A6 should be 2056910 or the memory/transaction sections should be referencing 281750813 and 270492367?
Is there some kind of masking that needs to be applied to A5 and A6 before the test is run?

Thanks

**Comment by greg904** [comment]
Yes, the 68K uses a 24-bit address bus, so the high byte of the addresses is ignored:
```
281750813 & 0x00FFFFFF = 13315357
270492367 & 0x00FFFFFF = 2056911
```

**Comment by pi1541** [comment]
Awesome, thanks!
