### ISSUE TITLE
65816: Incorrect final address for instructions with stack-relative addressing in emulation mode

### ISSUE THREAD

**Issue by qookei** [TomHarte/ProcessorTests#25]
For example, in test "03 e 10000" (which is `ORA d, S`), S is `$0143`, the operand is `$31`,
so the resultant address should be `$0174`, but the test instead expects `$b374`. AFAICU
stack-relative addressing does not have any page wrapping rules (vs. e.g. direct page
relative), and I don't see how one would arrive at page `$b3` anyway.

Worth noting that all of the native mode tests for stack-relative instructions are fine, only
emulation mode tests are affected.

Relevant part of test:
```json
"initial": {
    ...
    "s": 323,
    ...
},
...
"cycles": [
    [16255905, 3, "dp-remx-"],
    [16255906, 49, "-p-remx-"],
    [16255906, null, "---remx-"],
    [45940, 78, "d--remx-"]
]
```

My test suite runner output:
![image](https://user-images.githubusercontent.com/50294583/221425274-9303cf83-6d99-4953-bd66-f85842fdd2be.png)

**Comment by TomHarte** [comment]
Agreed that these are in error; the linked pull request likely solves the issue but I'm going to spot check a little before hitting merge.

**Comment by qookei** [comment]
PR #29 makes all the stack-relative instruction tests pass in my emulator

**Comment by TomHarte** [comment]
Cool; thanks for the report! Please don't hesitate to file further bugs if anything else comes up.
