### ISSUE TITLE
[68000] RTS tests broken

### ISSUE THREAD

**Issue by DennisOSRM** [TomHarte/ProcessorTests#31]
First of all, thank you very much for providing these tests. They are super helpful.

It seems the `RTS` test set contains a number of broken test instances, e.g. the following test where the cpu is in supervisor mode according to `sr` flags. 

```
{
	"name": "4e75 [RTS] 2",
	"initial": {
		...
		"usp": 4079683792,
		"ssp": 2048,
		"sr": 10014,
		"pc": 3072,
		"prefetch": [20085, 25783],
		"ram": [
			[5123, 17],
			[5122, 64],
			[15, 0],
			[5121, 50],
			[12, 0],
			[14, 20],
			[5120, 11],
			[2051, 177],
			[2050, 57],
			[2049, 60],
			[13, 0],
			[2048, 82]
		]
	},
	"final": {
		...
		"usp": 4079683792,
		"ssp": 2038,
		"sr": 10014,
		"pc": 5120,
		"prefetch": [2866, 16401],
		"ram": [
			[13, 0],
			[12, 0],
			[5123, 17],
			[2041, 60],
			[5122, 64],
			[2040, 82],
			[5121, 50],
			[15, 0],
			[2039, 126],
			[2043, 177],
			[2042, 57],
			[2045, 117],
			[2044, 78],
			[2047, 30],
			[2046, 39],
			[2051, 173],
			[2050, 57],
			[5120, 11],
			[14, 20],
			[2038, 78],
			[2049, 60],
			[2048, 82]
		]
	},
	"length": 58,
	"transactions": [
		["r", 4, 5, 2048, ".w", 21052],
		["r", 4, 5, 2050, ".w", 14769],
		["n", 4],
		["w", 4, 5, 2050, ".w", 14765],
		["w", 4, 5, 2046, ".w", 10014],
		["w", 4, 5, 2048, ".w", 21052],
		["w", 4, 5, 2044, ".w", 20085],
		["w", 4, 5, 2042, ".w", 14769],
		["w", 4, 5, 2038, ".w", 20094],
		["w", 4, 5, 2040, ".w", 21052],
		["r", 4, 5, 12, ".w", 0],
		["r", 4, 5, 14, ".w", 5120],
		["r", 4, 6, 5120, ".w", 2866],
		["n", 2],
		["r", 4, 6, 5122, ".w", 16401]
	]
}
```

First observation is that the length of the `ram` list is different and `RTS` is only modifying stack, pipeline, and registers, but not memory.  Second observation is that there are write operations on the bus, which is a bit puzzling since the `RTS` operation is defined as following:

```
RTS Return from subroutine
Operation: [PC] ← [M([SP])]; [SP] ← [SP] + 4
```

When `RTS` is executed in this example, it fetches a long word, ie. 32 bits, from the address given by `sp = 2038`. The four bytes  `[82, 60, 57, 177]` resemble return address `1379678641` which is not in the defined list of bytes in RAM.

**(updated)** Also, the length field seems off. According to documents, `RTS` has a cycle length of 16 including four read and no write cycles.

**Comment by TomHarte** [comment]
Just eyeballing it very briefly, the second read is an odd number so I think the generator is triggering an address error on the next attempt to access the PC, it now being unaligned.

Clearly I thought it was at some point, but I'll try to figure out whether that's correct behaviour.

**Comment by DennisOSRM** [comment]
Ah, of course, thank you for the clarification. The example should trigger an address error. I will update and fix my implementation.
