### ISSUE TITLE
Bad ADC test(s) for OP 0x69 (immediate addressing)

### ISSUE THREAD

**Issue by matthewoates** [TomHarte/ProcessorTests#34]
Given this test case:

```js
{
    "name": "69 0a e1",
    "initial": {
      "pc": 23290,
      "s": 148,
      "a": 2,
      "x": 112,
      "y": 254,
      "p": 175,
      "ram": [
        [
          23290,
          105
        ],
        [
          23291,
          10
        ],
        [
          23292,
          225
        ]
      ]
    },
    "final": {
      "pc": 23292,
      "s": 148,
      "a": 19,
      "x": 112,
      "y": 254,
      "p": 44,
      "ram": [
        [
          23290,
          105
        ],
        [
          23291,
          10
        ],
        [
          23292,
          225
        ]
      ]
    },
    "cycles": [
      [
        23290,
        105,
        "read"
      ],
      [
        23291,
        10,
        "read"
      ]
    ]
  }
  ```

The accumulator should be set to `ram[23291] + a + c`, which is `10 + 2 + 0`. Can someone explain why the expected value for the `a` register is `19` and not `12`?

**Comment by matthewoates** [comment]
Ah, similar to the memory mapping discrepancy, these tests are designed for the 6502 processor and not the NES specifically.

The NES deviates in functionality by ignoring the decimal flag (which is the issue I ran into here - I need to ignore all tests where the decimal flag is on) and these tests don't respect the NES's memory mapping either. (as intended)

**Comment by TomHarte** [comment]
No, that's a definite bug. The NES 6502 tests are intended to act exactly like the Ricoh, i.e. they're intended to maintain a decimal flag but ignore it. I'll have to figure out what's gone awry.

**Comment by TomHarte** [comment]
Cool. Then possibly I need to do a better job of labelling, but I'm going to close the issue, at least in part because I'm trying to get on top of these things.
