### ISSUE TITLE
Possible wrong cycle count for NES 6502 0C and 1/3/5/7/D/FC

### ISSUE THREAD

**Issue by rpgrca** [TomHarte/ProcessorTests#46]
I've been tinkering with some NES stuff and noticed a couple of inconsistencies in my log compared to the so-called [golden log](https://www.qmtpro.com/~nes/misc/nestest.log): at C6C9 cycle 14602 it executes an illegal opcode 0C which takes 4 cycles according to [Graham's table](http://www.oxyron.de/html/opcodes02.html) (next instruction EA starts executing at 14606, the registers shown are previous to executing the instruction in the same line).

```asm
C6C9  0C A9 A9 *NOP $A9A9 = A9                  A:AA X:97 Y:4E P:EF SP:F7 PPU:128,158 CYC:14602
C6CC  EA        NOP                             A:AA X:97 Y:4E P:EF SP:F7 PPU:128,170 CYC:14606
```

The 0c.json file only lists 3 cycles per scenario in similar cases:
```json
{ "name": "0c a2 a9",
"initial": { "pc": 59470, "s": 214, "a": 45, "x": 25, "y": 156, "p": 170, "ram": [ [59470, 12], [59471, 162], [59472, 169], [59473, 137]]},
"final": { "pc": 59473, "s": 214, "a": 45, "x": 25, "y": 156, "p": 170, "ram": [ [59470, 12], [59471, 162], [59472, 169], [59473, 137]]}, 
"cycles": [ [59470, 12, "read"], [59471, 162, "read"], [59472, 169, "read"]] },
```

The same table mentions that 1C, 3C, 5C, 6C, DC and FC all require 4 or 5 cycles, the extra one is added if the address crosses a page boundary, however in these files there are always 4 cycles listed.

It's literally impossible to find information for the NES specifically but I found other instances like [6502 Undocumented Opcodes](http://www.textfiles.com/programming/opcod6502.txt) from 1997 based on the Atari 8-bit 6502 which quotes a list by Joakim Atterhal and Freddy Offenga published in the Atari 8-bit disk magazine "Mega Maga-zine" issue 6, [Extra Instructions Of The 65XX Series CPU](http://www.ffd2.com/fridge/docs/6502-NMOS.extra.opcodes) based on Commodore 64 from 1995 where it mentions having used "The Complete Inner Space Anthology" by Karl J H Hildon from 1984-85 (found some [old scans of page 22](https://web.archive.org/web/20041204095041/http://www.ibiblio.org/pub/micro/commodore_in_situ/manuals/anthology/) which list the codes but not the cycles and quotes a couple of articles by Grainger and Raeto Collin West back in 1981), and [No More Secrets](https://csdb.dk/release/?id=198357) PDF from 2020 which borrows heavily from the previous documents (which also mentions it's focused on Commodore 64).

From "Extra Instructions Of The 65XX Series CPU":
```
SKW    ***
SKW skips next word (two bytes).
Opcodes: 0C, 1C, 3C, 5C, 7C, DC, FC.
Takes 4 cycles to execute.

To be dizzyingly precise, SKW actually performs a read operation.  It's 
just that the value read is not stored in any register.  Further, opcode 0C 
uses the absolute addressing mode.  The two bytes which follow it form the 
absolute address.  All the other SKW opcodes use the absolute indexed X 
addressing mode.  If a page boundary is crossed, the execution time of one 
of these SKW opcodes is upped to 5 clock cycles.
```

A few other routes mention findings rooting back Wolfgang Lorenz and his test suite for Commodore 64 and its MOS6510, however these aren't 100% compatible with 6502. I'm not sure if the files in your tests are correct or if they need to be modified but as I'm trying to emulate the NES as close as possible I will add an extra directive to decide whether I want 100% test compatibility or 100% nestest compatibility.

Great job with the set, it absolutely helped me nail a CPU emulator in one try using TDD!

**Comment by TomHarte** [comment]
Agreed that there seems to be a mismatch here. I'll see what I can do.

**Comment by rpgrca** [comment]
Hi there, I noticed you pushed a fix, thanks! I fixed my tests, ran then again and there are still some inconsistencies. The good news is that opcode 0C is correctly calculated now with 4 cycles instead of 3. On the other hand opcodes 1/3/5/7/D/FC always had 3 cycles, now they always have 5 cycles which means it still doesn't align correctly with the instructions I'm comparing to.

For example:
```json
[{ "name": "1c 1", "initial": {"pc": 19430, "s": 182, "a": 69, "x": 23, "y": 85, "p": 50, "ram": [[59081, 119], [19432, 230], [19431, 178], [19430, 28]]}, "final": {"pc": 19433, "s": 182, "a": 69, "x": 23, "y": 85, "p": 50, "ram": [[59081, 119], [19432, 230], [19431, 178], [19430, 28]]}, "cycles": [[19430, 28, "read"],[19431, 178, "read"],[19432, 230, "read"],[59081, 119, "read"],[59081, 119, "read"]]},
```

In this case the last read is not necessary because there's no page jump (the way I calculate that is to first calculate 230 << 8 | ((178 + 23) & 0xff), read from there, then calculate ((230 << 8 | 178) + 23) & 0xffff and if both addresses are equal as in this case I don't read as there was no page jump, however if the second calculated address is different from the first one I read from it as well). Could you check that out, please?

As a side note I also noticed you slightly changed the format of the file in those (before the first and last [] were in their own lines and they had three opcodes as name, now they have the opcode and and order) which might break some **bad** tests written for languages that might not parse JSON out of the box (C, C++ for example, which might discard the first line assuming it has an opening bracket).

**Comment by TomHarte** [comment]
Oh, I think I see the error on my part — logic is flowing down the 'zero, x; for a pending write' pathway, which is why it's always running for five cycles. Will endeavour to correct and better verify.

**Comment by rpgrca** [comment]
Awesome! Confirming everything is fixed! Thank you very much!
