### ISSUE TITLE
Inconsistency of the negative flag in decimal mode across 6502 emulators

### ISSUE THREAD

**Issue by lesserfish** [TomHarte/ProcessorTests#48]
I'm curious what was the emulator used to create the tests for the 6502. I'm having a hard time understanding the negative flags in some of the tests in the ADC test file (69.json).

For example, take a look at the following test:

> Name: "69 8d bc"
> 
> Initial State:
> pc:     41966   (0xa3ee)
> s:      163     (0xa3)  (10100011)
> a:      118     (0x76)  (01110110)
> x:      251     (0xfb)  (11111011)
> y:      160     (0xa0)  (10100000)
> p:      172     (0xac)  (10101100)
> [(a3ee , 69)(a3ef , 8d)(a3f0 , bc)]
> 
> Final State:
> CPU:
> pc:     41968   (0xa3f0)
> s:      163     (0xa3)  (10100011)
> a:      105     (0x69)  (01101001)
> x:      251     (0xfb)  (11111011)
> y:      160     (0xa0)  (10100000)
> p:      45      (0x2d)  (00101101)
> [(a3ee , 69)(a3ef , 8d)(a3f0 , bc)]

The instruction was: ADC #$8D (Adding 8D to the Accumulator with carry not set)

According to the [Mass:Werk Virtual 6502](https://www.masswerk.at/6502/), the negative flag should be set at the end of this instruction, but not according to the test.

I've looked at some other emulators ([[1]](https://github.com/SourMesen/Mesen-S/tree/master), [[2]](https://github.com/gianlucag/mos6502)) and found that the ADC operation with negative flag set is often very inconsistent when the accumulator or the operands hold undefined values (such as 0xFE or 0xA1, where one of the digits is larger than 0x9). This inconsistency happens at both the negative flag, as well as the actual accumulator value.

I'm building a 6502 emulator using these tests are a foundation, and I would really appreciate any highlight into how the negative flag is calculated when decimal mode is set.

I read somewhere that the negative flag is set regardless of the decimal mode, and it is set if the seventh bit of the accumulator is set.

But the following test shows something different:

> "69 8f b3"
> Initial State:
> pc:     63001   (0xf619)
> s:      130     (0x82)  (10000010)
> a:      227     (0xe3)  (11100011)
> x:      20      (0x14)  (00010100)
> y:      229     (0xe5)  (11100101)
> p:      111     (0x6f)  (01101111)
> [(f619 , 69)(f61a , 8f)(f61b , b3)]
> 
> Final State:
> pc:     63003   (0xf61b)
> s:      130     (0x82)  (10000010)
> a:      217     (0xd9)  (11011001)
> x:      20      (0x14)  (00010100)
> y:      229     (0xe5)  (11100101)
> p:      109     (0x6d)  (01101101)
> [(f619 , 69)(f61a , 8f)(f61b , b3)]

Here you can see that in the final state, the seventh bit of the accumulator is set, but the negative flag isn't.

Can anyone highlight to me how exactly the negative flag works in decimal mode?

Thank you very much!

**Comment by TomHarte** [comment]
It definitely needs work, but the current generator uses the code as at https://github.com/TomHarte/CLK/blob/598a889c6d45bbdcd0b2e41c79add3e48ee8e02c/Processors/6502/Implementation/6502Implementation.hpp#L284 ; regardless of the code quality it has been verified against the test at https://stardot.org.uk/forums/viewtopic.php?p=96927&sid=a7f243648f5c9529207c1474c59a3781#p96927 which:

>  is an exhaustive test, that tests all possible combinations of input to ADC and SBC in BCD mode, and checks the result, plus the C, Z, N and V flags

... and is known to pass on a real 6502, verifying its internal logic.

If you wanted to test directly against that, stripped of its platform specifics, then:

1. grab the binary at https://github.com/TomHarte/CLK/blob/master/OSBindings/Mac/Clock%20SignalTests/BCDTest/BCDTEST_beeb
2. within your emulated 6502, install that code at `$2900`;
3. put a $60 (i.e. RTS) at $FFEE (which is the entrypoint for a BBC-specific subroutine called OSWRCH that you can ignore if all you want is a thumbs up or down);
4. `JSR` to `$2900` and execute until you get an `RTS`;
5. check the value at `$84`; `0` is success, anything else is a failure.

**Comment by lesserfish** [comment]
Thanks!

I adapted your version of ADC and it works!
I'll check out the additional tests!
