### ISSUE TITLE
nes6502 README.md has incorrect sample

### ISSUE THREAD

**Issue by rpgrca** [TomHarte/ProcessorTests#51]
A minor issue: the [README.md](https://github.com/TomHarte/ProcessorTests/tree/main/nes6502) has a sample which is invalid. That was something I was stuck with for a day back when I started writing the emulator as instead of choosing a sample from a file I decided to use the one shown in the README (assumed it was correct, my mistake), then when I added more cases I noticed inconsistencies until I realized the original sample was wrong. Again, my mistake but I think it is simple to replace the one from the readme with any of the b1.json file which are all working correctly.

**Comment by TomHarte** [comment]
Done, thanks for spotting this!
