### ISSUE TITLE
Opcode 9C/9E: nes6502 Result Inconsistent with Test ROM

### ISSUE THREAD

**Issue by L-Spiro** [TomHarte/ProcessorTests#61]
If you write the result to the address as normal (write `VALUE` to `(ADDR)`) you will pass all of the JSON tests but you will fail the `07-abs_xy.nes` test ROM.  If you write `VALUE` to `(ADDR & 0xFF) | (VALUE << 8)` you will pass `07-abs_xy.nes` but fail JSON.
Note: Always prefer to pass test ROM’s, which have been verified against the hardware.

**Comment by TomHarte** [comment]
Noting for my own reference that https://github.com/blitzcode/neskell/tree/master/src/tests/unit contains further examples of Visual6502-verified tests for SHX, SHY et al that it would be worth investigating.

**Comment by TomHarte** [comment]
The pull request corrects the test set to match results generated by Visual6502 for 9c and 9e, and for 93, 9b and 9f — all of which share the same behaviour of ANDing something with what the top byte would be in a corrected address, and for using the ANDed result as the top byte if the address needs correction.
