### ISSUE TITLE
Test case issue `5ca0` `ADD.l Q, -(A0)`

### ISSUE THREAD

**Issue by javidsho** [TomHarte/ProcessorTests#68]
I don't understand why SSP and USP are being affected by ADD.l with A0. I checked the documentation and except for when you're using A7, I couldn't find any other rules for the stack pointer. 14 bytes are pushed on the stack while the stack shouldn't be affect at all. Could you please explain?

    5ca0 [ADD.l 6, -(A0)] 1
    Len = 52
    
    ==== Initial ====
    D0 = 1161947774         0x4541ea7e      0b01000101 01000001 11101010 01111110
    D1 = 3545793314         0xd3588322      0b11010011 01011000 10000011 00100010
    D2 = 6843363    0x686be3        0b00000000011010000110101111100011
    D3 = 1874953047         0x6fc18357      0b01101111 11000001 10000011 01010111
    D4 = 563902468  0x219c7804      0b00100001 10011100 01111000 00000100
    D5 = 1547052916         0x5c362774      0b01011100 00110110 00100111 01110100
    D6 = 2579288926         0x99bcd35e      0b10011001 10111100 11010011 01011110
    D7 = 2737427263         0xa329d33f      0b10100011 00101001 11010011 00111111
    A0 = 2507314547         0x95729573      0b10010101 01110010 10010101 01110011
    A1 = 1944242239         0x73e2c83f      0b01110011 11100010 11001000 00111111
    A2 = 1816450827         0x6c44d70b      0b01101100 01000100 11010111 00001011
    A3 = 3761516030         0xe0342dfe      0b11100000 00110100 00101101 11111110
    A4 = 2360450905         0x8cb19f59      0b10001100 10110001 10011111 01011001
    A5 = 3481664964         0xcf85fdc4      0b11001111 10000101 11111101 11000100
    A6 = 965124532  0x3986a1b4      0b00111001 10000110 10100001 10110100
    SSP = 2048      0x800   0b00000000000000000000100000000000
    USP = 2048      0x800   0b00000000000000000000100000000000
    PC = 3072       0xc00   0b00000000000000000000110000000000
    SR = 9997       0x270d  0b00000000000000000010011100001101
    Prefetch: 23712, 38522
    [MEMORY]
    12 (C) =        0       0
    13 (D) =        0       0
    14 (E) =        20      14
    15 (F) =        0       0
    5120 (1400) =   248     F8
    5121 (1401) =   56      38
    5122 (1402) =   3       3
    5123 (1403) =   251     FB
    
    ==== Final ====
    D0 = 1161947774         0x4541ea7e      0b01000101 01000001 11101010 01111110
    D1 = 3545793314         0xd3588322      0b11010011 01011000 10000011 00100010
    D2 = 6843363    0x686be3        0b00000000011010000110101111100011
    D3 = 1874953047         0x6fc18357      0b01101111 11000001 10000011 01010111
    D4 = 563902468  0x219c7804      0b00100001 10011100 01111000 00000100
    D5 = 1547052916         0x5c362774      0b01011100 00110110 00100111 01110100
    D6 = 2579288926         0x99bcd35e      0b10011001 10111100 11010011 01011110
    D7 = 2737427263         0xa329d33f      0b10100011 00101001 11010011 00111111
    A0 = 2507314543         0x9572956f      0b10010101 01110010 10010101 01101111
    A1 = 1944242239         0x73e2c83f      0b01110011 11100010 11001000 00111111
    A2 = 1816450827         0x6c44d70b      0b01101100 01000100 11010111 00001011
    A3 = 3761516030         0xe0342dfe      0b11100000 00110100 00101101 11111110
    A4 = 2360450905         0x8cb19f59      0b10001100 10110001 10011111 01011001
    A5 = 3481664964         0xcf85fdc4      0b11001111 10000101 11111101 11000100
    A6 = 965124532  0x3986a1b4      0b00111001 10000110 10100001 10110100
    SSP = 2034      0x7f2   0b00000000000000000000011111110010
    USP = 2034      0x7f2   0b00000000000000000000011111110010
    PC = 5120       0x1400  0b00000000000000000001010000000000
    SR = 9997       0x270d  0b00000000000000000010011100001101
    Prefetch: 63544, 1019
    [MEMORY]
    12 (C) =        0       0
    13 (D) =        0       0
    14 (E) =        20      14
    15 (F) =        0       0
    2034 (7F2) =    92      5C
    2035 (7F3) =    181     B5
    2036 (7F4) =    149     95
    2037 (7F5) =    114     72
    2038 (7F6) =    149     95
    2039 (7F7) =    111     6F
    2040 (7F8) =    92      5C
    2041 (7F9) =    160     A0
    2042 (7FA) =    39      27
    2043 (7FB) =    13      D
    2044 (7FC) =    0       0
    2045 (7FD) =    0       0
    2046 (7FE) =    12      C
    2047 (7FF) =    0       0
    5120 (1400) =   248     F8
    5121 (1401) =   56      38
    5122 (1402) =   3       3
    5123 (1403) =   251     FB

**Comment by sam-ellis** [comment]
The address is A0 is not aligned to a word boundary and so the instruction is causing an address error exception to occur. This is the reason for the memory transfers and other observed register changes.

**Comment by javidsho** [comment]
@sam-ellis Thank you for your response. The last thing pushed on stack is SSW according to the documentation, and the higher 11 bits are reserved. But for some reason, 0x5CB5 is pushed on stack in this test case. Why?
