### ISSUE TITLE
6502 0x20 opcode (Test 20 55 13) Incorrect?

### ISSUE THREAD

**Issue by gkjpettet** [TomHarte/ProcessorTests#77]
I think there is an issue with test `20 55 13`. My CPU emulator passes all tests apart from this one. I think the final status should be:

```no-highlight
A:  158
P:  230
PC: 4949 (0x1355)
X:  137
Y:  52

N V - B D I Z C
1 1 - 0 0 1 1 0 


------
Memory
------
Address | Value
341     | AD (173)
379     | 20 (32)
380     | 7E (126)
381     | 01 (1)
```

**Comment by pjsoberoi** [comment]
This is a tricky one, I had the same question. The instruction is overwriting itself as it's executing. 

Dup of https://github.com/TomHarte/ProcessorTests/issues/65.
